parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - eslint:recommended
  - 'plugin:@typescript-eslint/recommended'
  - prettier
plugins:
  - '@typescript-eslint'
  - prettier
root: true
rules:
  prettier/prettier: 2
  sort-keys:
    - error
    - asc
    - caseSensitive: true
      natural: false
